//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magaz2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib
    {
        public int id_game { get; set; }
        public byte[] Icon { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Genre { get; set; }
    }
}
